# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: CD pipeline

trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  containers:
    - container: go-di-example
      image: silicon-perigee-259504/go-di-example/image:latest
      endpoint: molly

steps:
- task: printAllVariables@1
  displayName: 'Print all variables'

- script: ls -al /bin/
  displayName: 'See if the di binary is in the expected location'
  
