# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: CD pipeline

trigger:
- prod

pool:
  vmImage: ubuntu-latest

resources:
  containers:
    - container: image
      endpoint: molly
      image: us-central1-docker.pkg.dev/silicon-perigee-259504/go-di-example

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    env
  displayName: 'Display the resource detail'
