# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: CD pipeline

trigger:
- prod

pool:
  vmImage: ubuntu-latest

container: 
  image: silicon-perigee-259504/go-di-example/image:40
  endpoint: molly

steps:
- script: ls -al /bin/
  displayName: 'See if the di binary is in the expected location'
  
