# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: CD pipeline

trigger:
- prod

pool:
  vmImage: ubuntu-latest

resources:
  containers:
    - container: go-di-example
      endpoint: molly
      image: silicon-perigee-259504/go/di-example/image:20

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo $(resources.container.go-di-example.type)
    echo $(resources.container.go-di-example.registry)
    echo $(resources.container.go-di-example.repository)
    echo $(resources.container.go-di-example.tag)
    echo $(resources.container.go-di-example.digest)
    echo $(resources.container.go-di-example.URI)
    echo $(resources.container.go-di-example.location)

  displayName: 'Display the resource detail'
